[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "geolocation=(self)"
    X-Frame-Options = "DENY"

[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/home.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/index.html"
  status = 200
